# Generated by Django 5.1.3 on 2024-12-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workout_intesity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='intesity',
            new_name='intensity',
        ),
    ]
