# Generated by Django 5.1.3 on 2024-12-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_rename_intesity_workout_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(default='low', max_length=20),
        ),
    ]
