# Generated by Django 5.1.3 on 2024-12-03 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_alter_workout_intensity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userworkoutplan',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='user_workout_plan',
            field=models.ForeignKey(blank='True', null='True', on_delete=django.db.models.deletion.CASCADE, to='workout.userworkoutplan'),
            preserve_default='True',
        ),
    ]
