# Generated by Django 5.1.3 on 2024-12-03 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_remove_userworkoutplan_workout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkoutplan',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user_workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workout.userworkoutplan'),
        ),
    ]
