# Generated by Django 5.1.3 on 2024-12-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_alter_userworkoutplan_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userworkoutplan',
            name='intensity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
