# Generated by Django 5.1.3 on 2024-12-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_userworkoutplan_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userworkoutplan',
            name='intensity',
            field=models.CharField(blank=True, default='low', max_length=20, null=True),
        ),
    ]
